Repository gazebosim/gz-fuel-tools, pull requests merged in 2020-12, with the labels that each got.

#139 Prepare for 4.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#141 Set keep alive on
  src/RestClient.cc
Labels: 🏰 citadel

#140 Support editing/patching model files
  include/ignition/fuel_tools/FuelClient.hh
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/cmd/cmdfuel.rb.in
  src/ign.cc
  src/ign.hh
Labels: 🏰 citadel

#143 4 to 5 11302020
  Changelog.md
  include/ignition/fuel_tools/FuelClient.hh
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/RestClient.cc
  src/WorldIdentifier.cc
  src/WorldIdentifier_TEST.cc
  src/cmd/cmdfuel.rb.in
  src/ign.cc
  src/ign.hh
  src/ign_src_TEST.cc
Labels: 🏢 edifice, 🔮 dome

#145 Prepare for 5.1.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🔮 dome

#146 Fix light map URI in materials
  src/LocalCache.cc
Labels: 🏢 edifice, 🔮 dome

#147 ⬆️ 5.1.1
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🔮 dome

#149 Document IGN_FUEL_CACHE_PATH on command line
  src/cmd/cmdfuel.rb.in
Labels: documentation, 🏰 citadel
