Repository gazebosim/gz-fuel-tools, pull requests merged in 2020-11, with the labels that each got.

#132 Update Backpack model to fix tests
  src/ign_src_TEST.cc
Labels: tests, 📜 blueprint

#131 3 to 4
  src/ign.cc
  src/ign_src_TEST.cc
Labels: 🏰 citadel

#133 4 to 5
  src/ign.cc
  src/ign_src_TEST.cc
Labels: 🏢 edifice, 🔮 dome

#130 Use lowercase resource and owner names when storing assets on disk
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/WorldIdentifier.cc
  src/WorldIdentifier_TEST.cc
  src/ign_src_TEST.cc
Labels: 📜 blueprint

#135 Prepare for 3.5.0 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#123 Download dependencies
  src/FuelClient.cc
  src/FuelClient_TEST.cc
Labels: 🏰 citadel

#137 3 to 4 11302020
  Changelog.md
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/WorldIdentifier.cc
  src/WorldIdentifier_TEST.cc
  src/ign_src_TEST.cc
Labels: 🏰 citadel
