Repository gazebosim/gz-fuel-tools, pull requests merged in 2020-08, with the labels that each got.

#94 Modernize actions CI
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
Labels: 📜 blueprint

#96 3 ➡️ 4
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  Changelog.md
Labels: 🏰 citadel

#97 4 ➡️ 5
  .github/ci-bionic/after_make.sh
  .github/ci-bionic/dependencies.yaml
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  Changelog.md
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/LocalCache.cc
Labels: 🔮 dome

#95 Added support for annotation parsing during model creation
  src/FuelClient.cc
Labels: 🔮 dome

#100 Fix test worlds
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/ign_src_TEST.cc
Labels: tests, 📜 blueprint

#101 Removed repeated installation instructions
  README.md
  tutorials/01_installation.md
Labels: enhancement, 🔮 dome

#102 3 ➡️ 4
  include/ignition/fuel_tools/CollectionIdentifier.hh
  include/ignition/fuel_tools/FuelClient.hh
  src/CMakeLists.txt
  src/CollectionIdentifier.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/cmd/cmdfuel.rb.in
  src/ign.cc
  src/ign.hh
  src/ign_src_TEST.cc
Labels: 🏰 citadel

#103 👩‍🌾 Fix Windows build
  include/ignition/fuel_tools/Result.hh
  src/CollectionIdentifier_TEST.cc
  src/Result.cc
  src/Result_TEST.cc
Labels: Windows, bug

#104 3.4.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#110 Fixed test - Download world 2
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/ign_src_TEST.cc
Labels: tests, 🔮 dome

#107 👩‍🌾 Make Windows 🟢
  .github/ci/packages.apt
  CMakeLists.txt
  configure.bat
  include/ignition/fuel_tools/ClientConfig.hh
  include/ignition/fuel_tools/CollectionIdentifier.hh
  include/ignition/fuel_tools/FuelClient.hh
  include/ignition/fuel_tools/LocalCache.hh
  include/ignition/fuel_tools/Model.hh
  include/ignition/fuel_tools/ModelIdentifier.hh
  include/ignition/fuel_tools/ModelIter.hh
  include/ignition/fuel_tools/ModelIterPrivate.hh
  include/ignition/fuel_tools/ModelPrivate.hh
  include/ignition/fuel_tools/RestClient.hh
  include/ignition/fuel_tools/Result.hh
  include/ignition/fuel_tools/WorldIdentifier.hh
  include/ignition/fuel_tools/WorldIter.hh
  include/ignition/fuel_tools/WorldIterPrivate.hh
  src/CMakeLists.txt
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier_TEST.cc
  src/WorldIdentifier_TEST.cc
  src/Zip.cc
  src/Zip_TEST.cc
  src/ign_src_TEST.cc
  test/CMakeLists.txt
  test/integration/zip.cc
Labels: Windows, tests, 📜 blueprint

#112 3 ➡️ 4
  .github/ci/packages.apt
  CMakeLists.txt
  configure.bat
  include/ignition/fuel_tools/ClientConfig.hh
  include/ignition/fuel_tools/CollectionIdentifier.hh
  include/ignition/fuel_tools/FuelClient.hh
  include/ignition/fuel_tools/LocalCache.hh
  include/ignition/fuel_tools/Model.hh
  include/ignition/fuel_tools/ModelIdentifier.hh
  include/ignition/fuel_tools/ModelIter.hh
  include/ignition/fuel_tools/ModelIterPrivate.hh
  include/ignition/fuel_tools/ModelPrivate.hh
  include/ignition/fuel_tools/RestClient.hh
  include/ignition/fuel_tools/Result.hh
  include/ignition/fuel_tools/WorldIdentifier.hh
  include/ignition/fuel_tools/WorldIter.hh
  include/ignition/fuel_tools/WorldIterPrivate.hh
  src/CMakeLists.txt
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier_TEST.cc
  src/Result.cc
  src/Result_TEST.cc
  src/WorldIdentifier_TEST.cc
  src/Zip.cc
  src/Zip_TEST.cc
  src/ign.cc
  src/ign_TEST.cc
  src/ign_src_TEST.cc
  test/CMakeLists.txt
  test/integration/zip.cc
Labels: Windows, 🏰 citadel

#114 4.2.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#116 Missing download j option
  CMakeLists.txt
  Changelog.md
  src/cmd/cmdfuel.rb.in
Labels: 🏰 citadel
