Repository gazebosim/gz-fuel-tools, pull requests merged in 2020-05, with the labels that each got.

#63 [ign-fuel-tools3] Workflow updates
  .github/CODEOWNERS
  .github/ci-bionic/after_make.sh
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 📜 blueprint

#68 [ign-fuel-tools4] Update BitBucket links
  CONTRIBUTING.md
  Changelog.md
  INSTALL_WINDOWS.md
  Migration.md
  README.md
  bitbucket-pipelines.yml
  configure.bat
  doc/header.html
  src/ModelIter.cc
  src/Zip_TEST.cc
  tutorials/01_installation.md
  tutorials/02_configuration.md
  tutorials/04_cpp_api.md
Labels: 🏰 citadel

#64 [ign-fuel-tools4] Workflow updates
  .github/CODEOWNERS
  .github/ci-bionic/after_make.sh
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 🏰 citadel, 🔮 dome

#70 Fix URL path encoding
  CMakeLists.txt
  Changelog.md
  src/RestClient.cc
Labels: 📜 blueprint
