Repository gazebosim/gz-fuel-tools, pull requests merged in 2020-06, with the labels that each got.

#72 3 ➡️ 4
  Changelog.md
  src/RestClient.cc
Labels: 🏰 citadel, 🔮 dome

#75 Openrobotics org name
  README.md
  example/details.cc
  example/download.cc
  include/ignition/fuel_tools/FuelClient.hh
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/cmd/cmdfuel.rb.in
  src/ign_src_TEST.cc
  tutorials/03_command_line.md
Labels: 📜 blueprint

#67 Added public/private editing
  .gitignore
  Changelog.md
  README.md
  include/ignition/fuel_tools/FuelClient.hh
  include/ignition/fuel_tools/ModelIdentifier.hh
  include/ignition/fuel_tools/RestClient.hh
  include/ignition/fuel_tools/Result.hh
  src/FuelClient.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/RestClient.cc
  src/Result.cc
  src/cmd/cmdfuel.rb.in
  src/ign.cc
  src/ign.hh
  tutorials/03_command_line.md
Labels: enhancement, 🏰 citadel

#69 License handling
  .gitignore
  Changelog.md
  include/ignition/fuel_tools/FuelClient.hh
  include/ignition/fuel_tools/JSONParser.hh
  src/FuelClient.cc
  src/JSONParser.cc
  src/JSONParser_TEST.cc
  src/ign.cc
Labels: 🏰 citadel

#76 Fix world tests
  src/FuelClient_TEST.cc
  src/ign_src_TEST.cc
Labels: 📜 blueprint
