Repository gazebosim/gz-fuel-tools, pull requests merged in 2021-05, with the labels that each got.

#184 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#178 Fixed windows download
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/Interface.cc
  src/Interface_TEST.cc
  src/LocalCache.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/ModelIter.cc
  src/WorldIdentifier_TEST.cc
  src/WorldIter.cc
  src/Zip.cc
  src/ign_src_TEST.cc
Labels: Windows, needs upstream release, 🏰 citadel

#187 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
Labels: 🏰 citadel
