Repository gazebosim/gz-fuel-tools, pull requests merged in 2021-03, with the labels that each got.

#169 5 ➡️ 6
  .github/ci/packages.apt
  CMakeLists.txt
  README.md
  bitbucket-pipelines.yml
  include/ignition/fuel_tools/ClientConfig.hh
  include/ignition/fuel_tools/FuelClient.hh
  src/ClientConfig.cc
  src/FuelClient.cc
  src/LocalCache.cc
  src/cmd/cmdfuel.rb.in
  tutorials/01_installation.md
  tutorials/02_configuration.md
  tutorials/03_command_line.md
Labels: 🏢 edifice

#171 4 ➡️ 5
  .github/workflows/ci.yml
  README.md
  bitbucket-pipelines.yml
  src/Zip_TEST.cc
Labels: 🔮 dome

#173 5 ➡️ 6
  .github/workflows/ci.yml
  README.md
  bitbucket-pipelines.yml
  src/Zip_TEST.cc
Labels: beta, 🏢 edifice

#175 🎈 6.0.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏢 edifice

#176 Include windows instructions in examples README.md
  example/README.md
  tutorials/02_configuration.md
  tutorials/04_cpp_api.md
Labels: Windows, documentation, 🏢 edifice
