Repository gazebosim/gz-fuel-tools, pull requests merged in 2021-11, with the labels that each got.

#199 APIs for retrieving models in parallel
  include/ignition/fuel_tools/FuelClient.hh
  src/ClientConfig_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/ign.cc
Labels: 🔮 dome

#213 FuelClient.cc: include <deque>
  src/FuelClient.cc
  src/ign.cc
  src/ign_src_TEST.cc
Labels: 🏰 citadel, Gazebo 1️1️

#219 Fix cmdfuel ruby script generation on Windows with MSVC
  src/cmd/CMakeLists.txt
Labels: Windows, 🏯 fortress, 🌱 garden
