Repository gazebosim/gz-fuel-tools, pull requests merged in 2021-01, with the labels that each got.

#151 Use semantic version and prevent crash if version is missing
  .github/ci/packages.apt
  CMakeLists.txt
  src/LocalCache.cc
Labels: 🏰 citadel

#158 Bump in edifice: ign-msgs7
  .github/ci/packages.apt
  CMakeLists.txt
  configure.bat
  include/ignition/fuel_tools/FuelClient.hh
  tutorials/01_installation.md
  tutorials/02_configuration.md
  tutorials/04_cpp_api.md
Labels: 🏢 edifice

#162 Add Windows Installation
  README.md
  tutorials/01_installation.md
Labels: 🏰 citadel

#164 Fix Windows CI: fuel-tools5 use msgs6
  bitbucket-pipelines.yml
  configure.bat
  tutorials/01_installation.md
Labels: 🔮 dome

#156 Included private-token to config.yaml
  include/ignition/fuel_tools/ClientConfig.hh
  include/ignition/fuel_tools/FuelClient.hh
  src/ClientConfig.cc
  src/FuelClient.cc
  tutorials/02_configuration.md
  tutorials/03_command_line.md
Labels: 🏢 edifice, 🔮 dome

#161 Unset DELETE method on Windows
  include/ignition/fuel_tools/RestClient.hh
  include/ignition/fuel_tools/Result.hh
Labels: Windows, 🏢 edifice
