Repository gazebosim/gz-fuel-tools, pull requests merged in 2022-07, with the labels that each got.

#273 Remove unused files (bitbucket-pipelines, docs)
  INSTALL_WINDOWS.md
  bitbucket-pipelines.yml
  doc/CMakeLists.txt
  doc/footer.html
  doc/header.html
  doc/ignition.in
  doc/tutorials-footer.html
  doc/tutorials-header.html
  doc/tutorials.in
Labels: 🏰 citadel, Gazebo 1️1️

#272 ign -> gz CMake, Python, Partial Source, and File Migrations : gz-fuel-tools
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  CMakeLists.txt
  Changelog.md
  INSTALL_WINDOWS.md
  api.md.in
  conf/CMakeLists.txt
  configure.bat
  doc/CMakeLists.txt
  doc/gz.in
  doc/header.html
  doc/tutorials.in
  example/configure.bat
  include/CMakeLists.txt
  include/gz/fuel_tools/Helpers.hh
  include/gz/fuel_tools/config.hh.in
  src/FuelClient.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdfuel.rb.in
  tutorials.md.in
  tutorials/01_installation.md
Labels: 🌱 garden, ign to gz

#274 Merge ign-fuel-tools4 ➡️ ign-fuel-tools7
  INSTALL_WINDOWS.md
  doc/CMakeLists.txt
  doc/footer.html
  doc/header.html
  doc/ignition.in
  doc/tutorials-footer.html
  doc/tutorials-header.html
  doc/tutorials.in
Labels: 🏯 fortress

#275 ign -> gz Provisional Finale: Source Migration : gz-fuel-tools
  include/gz/fuel_tools/gz_auto_headers.hh.in
Labels: 🌱 garden, ign to gz

#276 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, tests, Gazebo 1️1️, QA

#277 4 ➡️ 7
  README.md
Labels: 🏯 fortress, QA

#278 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  conf/CMakeLists.txt
  include/ignition/fuel_tools/config.hh.in
  tutorials.md.in
Labels: ign to gz

#279 Merge ign-fuel-tools3 ➡️ ign-fuel-tools4
  CMakeLists.txt
  api.md.in
  conf/CMakeLists.txt
  include/ignition/fuel_tools/config.hh.in
  tutorials.md.in
Labels: 🏰 citadel, Gazebo 1️1️

#280 Merge ign-fuel-tools4 ➡️ ign-fuel-tools7
  CMakeLists.txt
  api.md.in
  conf/CMakeLists.txt
  include/ignition/fuel_tools/config.hh.in
  tutorials.md.in
Labels: 🏯 fortress

#281 Merge ign-fuel-tools7 ➡️ main
  INSTALL_WINDOWS.md
  README.md
  doc/CMakeLists.txt
  doc/footer.html
  doc/gz.in
  doc/header.html
  doc/tutorials-footer.html
  doc/tutorials-header.html
  doc/tutorials.in
  src/CollectionIdentifier_TEST.cc
  src/FuelClient_TEST.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier_TEST.cc
Labels: 🌱 garden
