Repository gazebosim/gz-fuel-tools, pull requests merged in 2022-03, with the labels that each got.

#235 Print error when unzipping fails to save a file
  src/Zip.cc
Labels: 🏰 citadel, Gazebo 1️1️

#237 Fix trailing slash expectations in failing tests
  src/ClientConfig_TEST.cc
  src/LocalCache_TEST.cc
Labels: tests, 🏢 edifice

#238 6 ➡️ 7
  src/ClientConfig_TEST.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/LocalCache_TEST.cc
  src/ign_src_TEST.cc
Labels: 🏯 fortress

#236 Add Ubuntu Jammy CI
  .github/workflows/ci.yml
Labels: tests, 🏯 fortress

#239 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  README.md
Labels: 🌱 garden

#241 Merge part of 7 -> main
  Changelog.md
  include/ignition/fuel_tools/FuelClient.hh
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier_TEST.cc
  src/WorldIdentifier_TEST.cc
  src/cmd/CMakeLists.txt
  src/ign.cc
  src/ign_src_TEST.cc
Labels: 🌱 garden

#242 4 ➡️ 6
  src/Zip.cc
Labels: 🏢 edifice

#240 Merge 7 -> main
  .github/workflows/ci.yml
  include/ignition/fuel_tools/Interface.hh
  src/Interface.cc
  src/Interface_TEST.cc
Labels: 🌱 garden
