Repository gazebosim/gz-fuel-tools, pull requests merged in 2022-06, with the labels that each got.

#255 🎈 4.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#257 Disable staging-fuel.ignitionrobotics.org test
  src/ign_TEST.cc
  src/ign_src_TEST.cc
Labels: 🏰 citadel, Gazebo 1️1️

#260 Merge ign-fuel-tools4 ➡️ ign-fuel-tools7
  Changelog.md
  include/ignition/fuel_tools/Interface.hh
  src/ign_TEST.cc
  src/ign_src_TEST.cc
Labels: 🏯 fortress

#264 [ign -> gz] CMake functions
  CMakeLists.txt
  conf/CMakeLists.txt
  conf/fuel.yaml.in
  include/gz/fuel_tools/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#259 ign -> gz Macro Migration : gz-fuel-tools
  Migration.md
  README.md
  conf/fuel.yaml.in
  include/gz/fuel_tools/ClientConfig.hh
  include/gz/fuel_tools/FuelClient.hh
  include/gz/fuel_tools/Helpers.hh
  include/gz/fuel_tools/Interface.hh
  include/ignition/fuel_tools/Helpers.hh
  src/ClientConfig.cc
  src/FuelClient_TEST.cc
  src/cmd/cmdfuel.rb.in
  src/ign.cc
  src/ign.hh
  src/ign_TEST.cc
  test/test_config.h.in
Labels: 🌱 garden, ign to gz

#262 ign -> gz CLI Migration : gz-fuel-tools
  CMakeLists.txt
  Changelog.md
  INSTALL_WINDOWS.md
  README.md
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/cmdfuel.rb.in
  src/gz.cc
  src/gz.hh
  src/gz_TEST.cc
  src/gz_src_TEST.cc
  tutorials/01_installation.md
  tutorials/03_command_line.md
Labels: 🌱 garden, ign to gz

#267 Rename CMake project to gz
  CMakeLists.txt
  doc/ignition.in
  example/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
Labels: 🌱 garden

#268 ign -> gz Partial Docs Migration and Project Name Followups : gz-fuel-tools
  .github/ci/after_make.sh
  Changelog.md
  INSTALL_WINDOWS.md
  Migration.md
  README.md
  api.md.in
  configure.bat
  example/README.md
  src/Helpers_TEST.cc
  src/LocalCache.cc
  tutorials.md.in
  tutorials/01_installation.md
  tutorials/03_command_line.md
Labels: 🌱 garden
