Repository gazebosim/gz-fuel-tools, pull requests merged in 2022-08, with the labels that each got.

#282 ign -> gz Migrate config and log directories : gz-fuel-tools
  README.md
Labels: 🌱 garden, ign to gz

#284 ign -> gz : Remove redundant namespace references
  src/ClientConfig.cc
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier_TEST.cc
  src/ModelIter_TEST.cc
  src/RestClient.cc
  src/Result_TEST.cc
  src/WorldIdentifier_TEST.cc
  src/WorldIter.cc
  src/WorldIter_TEST.cc
  src/Zip.cc
  src/Zip_TEST.cc
  test/integration/zip.cc
Labels: 🏰 citadel, ign to gz

#263 A more minimal Ignition to Gazebo server rename effort
  include/ignition/fuel_tools/ModelIdentifier.hh
  src/ClientConfig.cc
  src/ClientConfig_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/LocalCache.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
Labels: bug, 🏰 citadel, Gazebo 1️1️, ign to gz

#288 Merge ign-fuel-tools4 ➡️ ign-fuel-tools7
  include/ignition/fuel_tools/ModelIdentifier.hh
  src/ClientConfig.cc
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/LocalCache.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/ModelIter_TEST.cc
  src/RestClient.cc
  src/Result_TEST.cc
  src/WorldIdentifier_TEST.cc
  src/WorldIter.cc
  src/WorldIter_TEST.cc
  src/Zip.cc
  src/Zip_TEST.cc
  test/integration/zip.cc
Labels: 🏯 fortress

#287 Gz cache
  Migration.md
  src/ClientConfig.cc
  src/ClientConfig_TEST.cc
Labels: 🌱 garden, ign to gz

#289 🎈 4.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#292 🎈 7.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
