Repository gazebosim/gz-fuel-tools, pull requests merged in 2023-03, with the labels that each got.

#331 Allow Curl redirect on get
  src/RestClient.cc
Labels: 🏰 citadel

#334 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel

#337 4.8.2 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#341 Forward port 4 to 7 (Just changelog)
  Changelog.md
Labels: 🏯 fortress

#339 7.2.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#344 Merge ign-fuel-tools7 ➡️ gz-fuel-tools8
  .github/workflows/ci.yml
  COPYING
  Changelog.md
  LICENSE
  src/RestClient.cc
Labels: 🌱 garden

#345 7.2.2 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#346 Forward port 7 to 8
  Changelog.md
  src/FuelClient.cc
  src/RestClient.cc
Labels: 🌱 garden
