Repository gazebosim/gz-fuel-tools, pull requests merged in 2023-04, with the labels that each got.

#348 Forward port 8 to main
  COPYING
  Changelog.md
  LICENSE
  src/FuelClient.cc
  src/JSONParser.cc
  src/RestClient.cc
Labels: 🎵 harmonic

#351 Disable all LocalCache Tests for Windows
  src/LocalCache_TEST.cc
Labels: 🌱 garden

#350 Reflect pagination of RESTful requests in iterator API
  include/gz/fuel_tools/FuelClient.hh
  include/gz/fuel_tools/ModelIterPrivate.hh
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/ModelIter.cc
Labels: 🏰 citadel
