Repository gazebosim/gz-fuel-tools, pull requests merged in 2023-08, with the labels that each got.

#366 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#367 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden

#368 Prepare for 8.1.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#369 Merge gz-fuel-tools8 ➡️ main
  .github/workflows/triage.yml
  Changelog.md
Labels: 🎵 harmonic

#364 Remove ignition
  include/CMakeLists.txt
  include/ignition/fuel_tools.hh
  include/ignition/fuel_tools/ClientConfig.hh
  include/ignition/fuel_tools/CollectionIdentifier.hh
  include/ignition/fuel_tools/Export.hh
  include/ignition/fuel_tools/FuelClient.hh
  include/ignition/fuel_tools/Helpers.hh
  include/ignition/fuel_tools/Interface.hh
  include/ignition/fuel_tools/JSONParser.hh
  include/ignition/fuel_tools/Model.hh
  include/ignition/fuel_tools/ModelIdentifier.hh
  include/ignition/fuel_tools/ModelIter.hh
  include/ignition/fuel_tools/RestClient.hh
  include/ignition/fuel_tools/Result.hh
  include/ignition/fuel_tools/WorldIdentifier.hh
  include/ignition/fuel_tools/WorldIter.hh
  include/ignition/fuel_tools/Zip.hh
  include/ignition/fuel_tools/config.hh
  src/ClientConfig.cc
  src/ClientConfig_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  test/integration/deprecated_TEST.cc
Labels: beta, 🎵 harmonic
