Repository gazebosim/gz-fuel-tools, pull requests merged in 2023-01, with the labels that each got.

#319 Change backpack model version 2->3
  src/gz_src_TEST.cc
Labels: 🏯 fortress

#320 port: 7 to 8 2023-01-25
  Changelog.md
  src/gz_src_TEST.cc
Labels: 🌱 garden

#318 Fix model downloads for ignitionrobotics.org URIs
  Migration.md
  src/CMakeLists.txt
  src/ClientConfig.cc
  src/ClientConfig_TEST.cc
  src/FuelClient_TEST.cc
Labels: 🏰 citadel
