Repository gazebosim/gz-fuel-tools, pull requests merged in 2023-09, with the labels that each got.

#372 Update 04_cpp_api.md
  tutorials/04_cpp_api.md
Labels: 🎵 harmonic

#371 Update README.md
  README.md
Labels: 🎵 harmonic

#374 Drop focal from fuel_tools9 forward
  .github/workflows/ci.yml
Labels: 🎵 harmonic

#375 Modifies the use of ign for gz in installation tutorial
  tutorials/01_installation.md
Labels: beta, 🎵 harmonic

#377 added script to update assets to gz
  tools/gz-update-assets.py
Labels: 🌱 garden

#382 Update changelogs and Prepare for 9.0.0~pre2 Release
  CMakeLists.txt
  Changelog.md
Labels: beta, 🎵 harmonic

#383 Prepare for 9.0.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
