Repository gazebosim/gz-fuel-tools, pull requests merged in 2023-06, with the labels that each got.

#359 7.3.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#358 Merge gz-fuel-tools8 ➡️ main
  src/LocalCache_TEST.cc
Labels: 🎵 harmonic

#357 Minor cleanup
  src/ClientConfig.cc
  src/FuelClient.cc
  src/Interface.cc
  src/Model.cc
  src/ModelIdentifier.cc
  src/Model_TEST.cc
  src/WorldIdentifier.cc
Labels: 🌱 garden

#328 Support for bazel in Garden
  BUILD.bazel
  CMakeLists.txt
  src/CMakeLists.txt
  src/ClientConfig_TEST.cc
  src/FuelClient_TEST.cc
  src/Interface_TEST.cc
  src/LocalCache_TEST.cc
  src/RestClient_TEST.cc
  test/BUILD.bazel
Labels: 🌱 garden

#352 Deprecated non-relocatable macro
  include/gz/fuel_tools/config.hh.in
Labels: 🌱 garden
