Repository gazebosim/gz-fuel-tools, pull requests merged in 2024-01, with the labels that each got.

#393 Update CI badges in README
  README.md
Labels: 🎵 harmonic

#395 Merge gz-fuel-tools9 :arrow_right: main
  include/gz/fuel_tools/FuelClient.hh
  include/gz/fuel_tools/Helpers.hh
  src/CollectionIdentifier_TEST.cc
  src/FuelClient.cc
  src/FuelClient_TEST.cc
  src/Helpers.cc
  src/Helpers_TEST.cc
  src/LocalCache.cc
  src/LocalCache_TEST.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/ServerConfig.cc
  src/WorldIdentifier.cc
  src/WorldIdentifier_TEST.cc
Labels: 🏛️ ionic

#396 Tidy nested namespaces
  include/gz/fuel_tools/ClientConfig.hh
  include/gz/fuel_tools/CollectionIdentifier.hh
  include/gz/fuel_tools/FuelClient.hh
  include/gz/fuel_tools/Helpers.hh
  include/gz/fuel_tools/HttpMethod.hh
  include/gz/fuel_tools/Interface.hh
  include/gz/fuel_tools/JSONParser.hh
  include/gz/fuel_tools/Model.hh
  include/gz/fuel_tools/ModelIdentifier.hh
  include/gz/fuel_tools/ModelIter.hh
  include/gz/fuel_tools/RestClient.hh
  include/gz/fuel_tools/Result.hh
  include/gz/fuel_tools/ResultType.hh
  include/gz/fuel_tools/ServerConfig.hh
  include/gz/fuel_tools/WorldIdentifier.hh
  include/gz/fuel_tools/WorldIter.hh
  include/gz/fuel_tools/Zip.hh
  src/CMakeLists.txt
  src/ClientConfig.cc
  src/ClientConfig_TEST.cc
  src/CollectionIdentifier.cc
  src/FuelClient.cc
  src/Helpers.cc
  src/Interface.cc
  src/JSONParser.cc
  src/LocalCache.cc
  src/LocalCache.hh
  src/Model.cc
  src/ModelIdentifier.cc
  src/ModelIter.cc
  src/ModelIterPrivate.hh
  src/ModelPrivate.hh
  src/RestClient.cc
  src/Result.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/WorldIdentifier.cc
  src/WorldIter.cc
  src/WorldIterPrivate.hh
  src/gz.cc
Labels: 🎵 harmonic

#398 🎈 4.9.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#397 port: 9 to 10
  README.md
  include/gz/fuel_tools/ClientConfig.hh
  include/gz/fuel_tools/CollectionIdentifier.hh
  include/gz/fuel_tools/FuelClient.hh
  include/gz/fuel_tools/Helpers.hh
  include/gz/fuel_tools/HttpMethod.hh
  include/gz/fuel_tools/Interface.hh
  include/gz/fuel_tools/JSONParser.hh
  include/gz/fuel_tools/Model.hh
  include/gz/fuel_tools/ModelIdentifier.hh
  include/gz/fuel_tools/ModelIter.hh
  include/gz/fuel_tools/RestClient.hh
  include/gz/fuel_tools/Result.hh
  include/gz/fuel_tools/ResultType.hh
  include/gz/fuel_tools/ServerConfig.hh
  include/gz/fuel_tools/WorldIdentifier.hh
  include/gz/fuel_tools/WorldIter.hh
  include/gz/fuel_tools/Zip.hh
  src/ClientConfig.cc
  src/CollectionIdentifier.cc
  src/FuelClient.cc
  src/Helpers.cc
  src/Interface.cc
  src/JSONParser.cc
  src/LocalCache.cc
  src/LocalCache.hh
  src/Model.cc
  src/ModelIdentifier.cc
  src/ModelIter.cc
  src/ModelIterPrivate.hh
  src/ModelPrivate.hh
  src/RestClient.cc
  src/Result.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/WorldIdentifier.cc
  src/WorldIter.cc
  src/WorldIterPrivate.hh
  src/gz.cc
Labels: 🏛️ ionic

#400 Merge ign-fuel-tools4 ➡️ ign-fuel-tools7
  Changelog.md
  src/gz_src_TEST.cc
Labels: 🏯 fortress

#399 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic
