Repository gazebosim/gz-fuel-tools, pull requests merged in 2024-08, with the labels that each got.

#427 Use Ubuntu 24.04 in Github Actions CI workflow
  .github/workflows/ci.yml
  README.md
  src/FuelClient_TEST.cc
  src/LocalCache.cc
Labels: beta, 🏛️ ionic

#426 Prepare for 7.3.1 Release
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏯 fortress

#432 Prepare for 9.1.0 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#433 Fix GCC warnings
  src/FuelClient.cc
Labels: 🏯 fortress

#434 Merge gz-fuel-tools9 ➡️ main
  Changelog.md
  include/gz/fuel_tools/CollectionIdentifier.hh
  include/gz/fuel_tools/ModelIdentifier.hh
  include/gz/fuel_tools/WorldIdentifier.hh
  src/CollectionIdentifier.cc
  src/CollectionIdentifier_TEST.cc
  src/ModelIdentifier.cc
  src/ModelIdentifier_TEST.cc
  src/WorldIdentifier.cc
  src/WorldIdentifier_TEST.cc
Labels: 🏛️ ionic

#435 Add missing URI header files
  src/CollectionIdentifier.cc
  src/WorldIdentifier.cc
Labels: 🎵 harmonic

#436 Require cmake 3.22.1
  CMakeLists.txt
  example/CMakeLists.txt
Labels: 🏛️ ionic

#437 Merge 9 -> main
  src/CollectionIdentifier.cc
  src/WorldIdentifier.cc
Labels: 🏛️ ionic

#438 Ionic Changelog
  Changelog.md
Labels: 🏛️ ionic

#439 Update badges to point to gz-fuel-tools10
  README.md
Labels: 🏛️ ionic

#440 Prepare for 10.0.0~pre1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏛️ ionic

#441 Prepare for gz-fuel-tools10.0.0~pre2 release
  CMakeLists.txt
Labels: 🏛️ ionic
