Repository gazebosim/gz-fuel-tools, pull requests merged in 2024-05, with the labels that each got.

#419 Fix a test
  src/gz_TEST.cc
Labels: 🌱 garden

#421 Fix tests pulling from wrong server
  src/gz_TEST.cc
  src/gz_src_TEST.cc
Labels: 🏰 citadel

#422 Fix tests pulling from wrong server (#421)
  src/gz_TEST.cc
  src/gz_src_TEST.cc
Labels: 🏯 fortress
